MONGO_URI = "mongodb+srv://andradelucasmo:Q0I9Yp9Ai6mWK1vI@cluster0.5kddnrk.mongodb.net/"
MONGO_DB = "games"
MONGO_COLLECTION = "steam_reviews"
TOPIC_REVIEWS_COLLECTION = "topic_reviews"
LDA_TOPICS_COLLECTION = "lda_topics"